// Economics of layout — golden calculations with explicit inputs, never default PPA/yield.
// node tests/test_layout_economy.js
"use strict";
const fs=require("fs"),path=require("path"),E=require("../lib/layout-economics.js");
const R=path.join(__dirname,"..");let ok=0,bad=0;
function check(k,v,extra){if(v){ok++;console.log("OK   "+k);}else{bad++;console.log("FAIL "+k+(extra?" → "+extra:""));}}
const near=(x,y,eps=1e-7)=>Math.abs(x-y)<eps;
function throws(fn,rx){try{fn();return false;}catch(e){return rx.test(String(e.message||e));}}
const p={energyKwhKwp:1000,capexEurKwp:1000,opexEurKwpYear:0,
  saleEurMwh:1000,discountPct:0,degradationPct:0,years:1};
const a=E.evaluate({kwp:1},p);
check("modelo es estimación NO bankable",a.status==="ESTIMACION_NO_BANKABLE");
check("1 kWp × 1000 kWh/kWp = 1 MWh",near(a.firstYearMwh,1));
check("CAPEX 1 kWp × 1000€/kWp = 1000€",near(a.capexEur,1000));
check("sin OPEX anual",near(a.annualOpexEur,0));
check("ingreso año1 1000€/MWh",near(a.annual[0].revenueEur,1000));
check("VAN a cero descuento con break-even = 0€",near(a.npvEur,0));
check("LCOE a descuento cero = 1000€/MWh",near(a.lcoeEurMwh,1000));
check("TIR 0% para una anualidad break-even",near(a.irrPct,0));
check("retorno simple al final del año1",a.paybackYears===1);
check("energía vitalicia de un solo año = 1 MWh",near(a.lifetimeMwh,1));
const a10=E.evaluate({kwp:1},{...p,saleEurMwh:1100});
check("ingreso 10% extra → VAN +100€",near(a10.npvEur,100));
check("IRR 10% en un año [-1000,+1100]",near(a10.irrPct,10));
const d10=E.evaluate({kwp:1},{...p,saleEurMwh:1100,discountPct:10});
check("descuento 10% → VAN 0",near(d10.npvEur,0));
const extra=E.evaluate({kwp:1,extraCivilEur:500},p);
check("CAPEX civil explícito suma 500€",near(extra.capexEur,1500));
check("extra civil sube LCOE a 1500€/MWh",near(extra.lcoeEurMwh,1500));
check("extra civil baja VAN 500€",near(extra.npvEur,-500));
const degrad=E.evaluate({kwp:1},{...p,years:2,degradationPct:10});
check("año1 sin degradar",near(degrad.annual[0].mwh,1));
check("año2 pierde 10% energía",near(degrad.annual[1].mwh,.9));
check("energy year1+y2=1.9",near(degrad.lifetimeMwh,1.9));
check("beneficio año2 incluye degradación",near(degrad.annual[1].cashFlowEur,900));
const opex=E.evaluate({kwp:2},{...p,opexEurKwpYear:25});
check("2 kWp ×25 €/kWp =50 €/año",near(opex.annualOpexEur,50));
check("año1 2MWh ×1000€ =2000€",near(opex.annual[0].revenueEur,2000));
check("flujo anual neto 1950€",near(opex.annual[0].cashFlowEur,1950));
check("NPV un año = -2000+1950 = -50",near(opex.npvEur,-50));
const c=E.compare({kwp:100},{kwp:95},p);
check("compare A original potencia",near(c.base.kwp,100));
check("compare B con menos potencia",near(c.proposed.kwp,95));
check("delta potencia B-A = -5kWp",near(c.deltaKwp,-5));
check("delta energía B-A = -5MWh",near(c.deltaYear1Mwh,-5));
check("mismo rendimiento relativo → LCOE igual",near(c.deltaLcoeEurMwh,0));
const cCivil=E.compare({kwp:100},{kwp:95,extraCivilEur:5000},p);
check("sobrecoste sube LCOE de B",cCivil.deltaLcoeEurMwh>0);
check("sobrecoste baja VAN de B",cCivil.deltaNpvEur<c.deltaNpvEur);
check("sin ventas, IRR no se inventa",E.evaluate({kwp:1},{...p,saleEurMwh:0}).irrPct===null);
check("sin CAPEX, IRR no se inventa",E.evaluate({kwp:1},{...p,capexEurKwp:0}).irrPct===null);
check("sin serie de cambio de signo, devuelve null",E.irr([1,2,3])===null);
check("sin layout aborta",throws(()=>E.evaluate(null,p),/Genera/));
check("layout de potencia nula aborta",throws(()=>E.evaluate({kwp:0},p),/potencia/));
check("no inventa producción específica",throws(()=>E.evaluate({kwp:1},{...p,energyKwhKwp:""}),/producción específica/));
check("no inventa CAPEX",throws(()=>E.evaluate({kwp:1},{...p,capexEurKwp:""}),/CAPEX/));
check("no inventa OPEX",throws(()=>E.evaluate({kwp:1},{...p,opexEurKwpYear:""}),/OPEX/));
check("no inventa precio PPA",throws(()=>E.evaluate({kwp:1},{...p,saleEurMwh:""}),/precio/));
check("no inventa descuento",throws(()=>E.evaluate({kwp:1},{...p,discountPct:""}),/descuento/));
check("no inventa degradación",throws(()=>E.evaluate({kwp:1},{...p,degradationPct:""}),/degradación/));
check("no inventa horizonte",throws(()=>E.evaluate({kwp:1},{...p,years:""}),/vida/));
check("rechaza energía negativa",throws(()=>E.evaluate({kwp:1},{...p,energyKwhKwp:-10}),/producción/));
check("rechaza OPEX negativo",throws(()=>E.evaluate({kwp:1},{...p,opexEurKwpYear:-1}),/OPEX/));
check("rechaza años mayores que 50",throws(()=>E.evaluate({kwp:1},{...p,years:51}),/vida/));
check("rechaza coste civil negativo",throws(()=>E.evaluate({kwp:1,extraCivilEur:-1},p),/civil/));
check("rechaza tasa <= -100%",throws(()=>E.evaluate({kwp:1},{...p,discountPct:-100}),/descuento/));
const html=fs.readFileSync(path.join(R,"generador-layout.html"),"utf8");
const bridge=fs.readFileSync(path.join(R,"lib/layout-economy-ui.js"),"utf8");
check("modelo de negocio integrado en el generador",html.includes('id="economyCard"'));
check("capturas guardan kWp del RES real, no suposición",/RES\.stats\.kWp/.test(bridge)&&/RESULTADO_REAL_DEL_GENERADOR/.test(bridge));
check("descuento, producción y precio son campos usuario",/id="finDiscount"/.test(html)&&/id="finYield"/.test(html)&&/id="finPrice"/.test(html));
check("sin dataset inventado (placeholder explícito)",/Del cálculo SolarGPT\/PVsyst/.test(html));
check("capturas A/B de alternativas geométricas",html.includes('id="finBase"')&&html.includes('id="finRisk"'));
check("mismo escenario hídrico para comparativa",/a\.sig!==b\.sig/.test(bridge));
check("ficheros economics locales",html.includes('src="lib/layout-economics.js"'));
check("adaptador UI compila",(()=>{try{new Function(bridge);return true;}catch(e){return false;}})());
check("se persisten solo hipótesis y alternativas, no cash flows",html.includes("st.finCases=FIN_CASES")&&!html.includes("st.finCashFlows="));
console.log("\n"+(bad?"FALLOS "+bad:"OK")+" · "+ok+" comprobaciones, "+bad+" rojos");
process.exitCode=bad?1:0;
