'use strict';
const assert=require('assert/strict');
const Search=require('../lib/layout-search.js');
const {loadEngine,cases}=require('./layout_search_cases.cjs');
let ok=0;
function check(name,value){assert.ok(value,name);ok++;console.log('OK   '+name);}
const engine=loadEngine();
const clone=x=>JSON.parse(JSON.stringify(x));
const fixed=c=>{const r=clone(c);delete r._xOff;delete r._yOff;return JSON.stringify(r);};
(async()=>{
  const data=[{x:[0,0],y:2},{x:[0.5,0.5],y:8},{x:[1,1],y:3}];
  const predict=Search.fit(data);
  check('el GP aprende valores diferentes de las observaciones',predict([0.5,0.5]).mean>predict([0,0]).mean+5.9);
  check('el GP interpola los datos sin inventar confianza perfecta',Math.abs(predict([0.5,0.5]).mean-8)<1e-4&&predict([0.5,0.5]).sd>0);
  check('la incertidumbre crece lejos de los datos',predict([0,1]).sd>predict([0,0]).sd*100);
  check('el modelo admite observaciones constantes',Number.isFinite(Search.fit(data.map(p=>({x:p.x,y:3})))([0.1,0.8]).sd));
  const cfg=cases().find(c=>c.name.includes('Finca dibujada')).config, before=JSON.stringify(cfg), seen=[];
  const opts={budget:16,seed:20260928,score:engine.puntuaLayout,compute:c=>{seen.push(clone(c));return engine.compute(c);}};
  const r=await Search.run(cfg,opts);
  check('se evalúan referencia y candidatos reales dentro del presupuesto',seen.length===16&&r.report.trace.length===16);
  check('el GP propone candidatos después de observar la parcela',r.report.trace.some(t=>t.stage==='gp'&&t.predictionBeforeEvaluation));
  check('todas las decisiones fijas del proyecto se conservan',seen.every(c=>fixed(c)===fixed(cfg)));
  check('el input del llamador permanece intacto',JSON.stringify(cfg)===before);
  check('los candidatos respetan el dominio declarado',seen.slice(1).every(c=>Math.abs(c._xOff)<=cfg.pitch/2&&Math.abs(c._yOff)<=cfg.pitch/2));
  check('el ganador nunca empeora la puntuación de referencia',r.best.score>=r.baseline.score);
  check('el ganador es una evaluación observada y supera QA',Search.validResult(r.best.result)&&r.report.trace[r.best.iteration].score===r.best.score);
  const regenerated=engine.compute(r.best.config);
  check('la configuración exportada reproduce el layout ganador',engine.puntuaLayout(regenerated)===r.best.score&&JSON.stringify(engine.toGeoJSON(regenerated))===JSON.stringify(engine.toGeoJSON(r.best.result)));
  const again=await Search.run(cfg,Object.assign({},opts,{compute:engine.compute}));
  check('misma semilla reproduce candidatos y decisiones',JSON.stringify(r.report.trace.map(t=>[t.x,t.y,t.score]))===JSON.stringify(again.report.trace.map(t=>[t.x,t.y,t.score])));
  const random=await Search.run(cfg,Object.assign({},opts,{compute:engine.compute,method:'random'}));
  check('aleatorio tiene el mismo presupuesto y diseño inicial',random.report.evaluations===16&&JSON.stringify(random.report.trace.slice(0,9).map(t=>[t.x,t.y,t.score]))===JSON.stringify(r.report.trace.slice(0,9).map(t=>[t.x,t.y,t.score])));
  check('la estrategia GP no es el barrido aleatorio renombrado',JSON.stringify(random.report.trace.map(t=>[t.x,t.y]))!==JSON.stringify(r.report.trace.map(t=>[t.x,t.y])));
  let calls=0;
  const stopped=await Search.run(cfg,{budget:16,compute:c=>{calls++;return engine.compute(c);},score:engine.puntuaLayout,shouldStop:()=>calls>=3});
  check('cancelar termina tras la evaluación en curso y conserva el mejor válido',stopped.report.status==='cancelled'&&calls===3&&stopped.best.score>=stopped.baseline.score);
  const invalid=await Search.run(cfg,{budget:8,compute:()=>({stats:{qa_geometria_ok:false,modules:999999,kWp:99999},avisos:[]}),score:()=>999999});
  check('un score enorme nunca permite aceptar geometría rechazada',invalid.best===null&&!invalid.report.improved&&invalid.report.trace.every(t=>!t.valid));
  let count=0;
  const failure=await Search.run(cfg,{budget:8,compute:c=>{if(count++>0)throw Error('engine unavailable');return engine.compute(c);},score:engine.puntuaLayout});
  check('un fallo de motor deja la referencia y queda trazado',failure.best.iteration===0&&failure.report.trace.slice(1).every(t=>t.error==='engine unavailable'));
  const nonfinite=await Search.run(cfg,{budget:8,compute:engine.compute,score:()=>NaN});
  check('no se promocionan puntuaciones NaN',nonfinite.best===null);
  await assert.rejects(()=>Search.run(cfg,{compute:engine.compute,score:engine.puntuaLayout,budget:Infinity}));
  check('se rechaza presupuesto no finito',true);
  await assert.rejects(()=>Search.run(Object.assign({},cfg,{mount:'mixto'}),opts));
  check('el alcance mono-montaje se comprueba antes de evaluar',true);
  check('el informe es serializable, incluye input y tiempos totales',JSON.parse(JSON.stringify(r.report)).input.coords.length>2&&r.report.elapsedMs>=r.report.computeMs);
  console.log('\n'+ok+' OK · 0 FALLOS');
})().catch(e=>{console.error('FAIL '+e.stack);process.exitCode=1;});
